<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Orchestration.Domain\Orchestration.Domain.csproj" />
        <ProjectReference Include="..\Orchestration.Infrastructure.Rabbit\Orchestration.Infrastructure.Rabbit.csproj" />
    </ItemGroup>

</Project>
