<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\InstrumentApp.DomainServices\InstrumentApp.DomainServices.csproj" />
        <ProjectReference Include="..\InstrumentApp.Infrastructure.Rabbit\InstrumentApp.Infrastructure.Rabbit.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Orchestration.WebApiClient" Version="1.0.0" />
    </ItemGroup>

</Project>
